apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kamailio
  name: kamailio-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kamailio
  template:
    metadata:
      labels:
        app: kamailio
    spec:
      containers:
        - image: 'kgopi424/kamailio'
          name: kamailio
          ports:
            - containerPort: 5060
        - command:
            - sipp
            - '-sn'
            - uas
            - '-rsa'
            - '10.244.0.21:5060'
            - '-trace_msg'
            - '-trace_err'
          image: 'pavan176/sipp:v3.7.0'
          imagePullPolicy: Always
          name: sipp
          ports:
            - containerPort: 5061
---
apiVersion: v1
kind: Service
metadata:
  name: kamailio-service
spec:
  ports:
    - port: 5060
      targetPort: 5060
  selector:
    app: kamailio
  type: NodePort
